name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}:run-${{ github.run_number }}

  update-image-tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: List files in the chart directory
        run: ls -l ./chart/

      - name: Update image tag in Rollout manifest
        run: |
          files=$(ls ./chart/*rollout.yaml)
          for file in $files; do
            echo "Updating image tag in $file"
            sed -i "s|image: ${IMAGE_REPO}:.*|image: ${IMAGE_REPO}:run-${{ github.run_number }}|" $file
          done
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./chart/*
          git commit -m "Update image tag to run-${{ github.run_number }}"
          git push --force-with-lease origin main
        env:
          IMAGE_REPO: ${{ env.IMAGE_REPO }}
