# Dockerfile.test

FROM python:3.9-slim

WORKDIR /tests

# Install dependencies
COPY requirements.txt /tests/
RUN pip install -r requirements.txt

# Copy the test code
COPY tests/ /tests/

CMD ["pytest", "-v"]
