apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
spec:
  metrics:
  - name: success-rate
    successCondition: "result[0] != 'NaN' and result[0] >= 90.0"
    failureCondition: "result[0] == 'NaN' or result[0] < 90.0"
    timeout: 120s
    provider:
      prometheus:
        address: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local
        query: |
          100 * sum(rate(flask_http_request_total{status="200"}[30m]))
          /
          (
            sum(rate(flask_http_request_total[30m])) > 0 
            ? sum(rate(flask_http_request_total[30m]))
            : NaN
          )
          
