apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "color-grid.fullname" . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "color-grid.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "color-grid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "color-grid.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause:
          duration: 1m
      - analysis:
          templates:
          - templateName: integration-test-results
      - setWeight: 20
      - pause:
          duration: 1m
      - analysis:
          templates:
          - templateName: success-rate-analysis
          - templateName: error-rate-analysis
      - setWeight: 50
      - pause:
          duration: 1m
      - analysis:
          templates:
          - templateName: response-latency-analysis
          - templateName: traffic-volume-analysis
      - setWeight: 80
      - pause:
          duration: 1m
      - analysis:
          templates:
          - templateName: success-rate-analysis
          - templateName: error-rate-analysis
      - setWeight: 100
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "color-grid.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        rollout-restart-hash: "{{ randAlphaNum 5 }}"
    spec:
      containers:
      - name: color-grid
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
