apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-analysis
spec:
  metrics:
  - name: error-rate
    successCondition: "result[0] <= 25.0"
    failureCondition: "result[0] > 25.0"
    provider:
      prometheus:
        address: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
        query: |
          100 * (sum(rate(http_requests_total{status=~"5.."}[5m])) or vector(0)) / (sum(rate(http_requests_total[5m])) or vector(1))
