apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test-results
spec:
  metrics:
  - name: integration-test-success-rate
    successCondition: "result >= 0.95"  # Adjust the condition based on actual metric logic
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
        query: |
          avg(integration_test_success_rate{app="color-grid"})
