apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test-results
spec:
  metrics:
  - name: integration-test-success-rate
    successCondition: "result[0] >= 0.95"  # Use the first result element for condition
    failureCondition: "result[0] < 0.95"   # Additional failure condition for clarity
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
        query: |
          avg(integration_test_success_rate{app="color-grid"}) or vector(0)
