apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  # labels:
  #   {{- include "color-grid.labels" . | nindent 4 }}
spec:
  replicas: "{{ .Values.replicaCount }}"
  # selector:
    # matchLabels:
    #   app: {{ include "color-grid.name" . }}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - analysis:
          templates:
          - templateName: success-rate-analysis
          args:
          - name: success-rate
            value: "80"
      - setWeight: 80
      - pause: {duration: 1m}
      - analysis:
          templates:
          - templateName: success-rate-analysis
          args:
          - name: success-rate
            value: "80"
      - setWeight: 100
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        # app: {{ include "color-grid.name" . }}
    spec:
      containers:
      - name: color-grid
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
