apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "color-grid.fullname" . }}
  labels:
    {{- include "color-grid.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "color-grid.name" . }}
  namespaceSelector:
    matchNames:
    - default  # Ensure this matches the namespace where your application is deployed
  endpoints:
  - port: http  # Ensure this matches the port name defined in your service
    interval: 30s
