apiVersion: v1
kind: Service
metadata:
  name: {{ include "color-grid.fullname" . }}
  labels:
    {{- include "color-grid.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "color-grid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    
