apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "color-grid.fullname" . }}
  labels:
    {{- include "color-grid.labels" . | nindent 4 }}
    release: prometheus-operator  # Ensures this is discovered by your Prometheus instance managed by Prometheus Operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "color-grid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - default  # Adjust this to match the namespace of your service if different
  endpoints:
  - port: http  # Ensure this matches the port name defined in your service
    interval: 30s
    path: /metrics  # Default metrics path for prometheus_flask_exporter
