apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
spec:
  metrics:
  - name: success-rate
    successCondition: "result[0] >= 60.0 and result[0] <= 100.0"
    failureCondition: "result[0] < 60.0"
    timeout: 120s
    provider:
      prometheus:
        address: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090
        query: |
          100 * sum(rate(flask_http_request_total{status="200"}[30m])) / sum(rate(flask_http_request_total[30m])) or vector(0)
