# templates/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: python-test-rollout
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
      - name: python-tests
        image: "{{ .Values.testImage.repository }}:{{ .Values.testImage.tag }}"
        imagePullPolicy: "{{ .Values.testImage.pullPolicy }}"
        ports:
        - containerPort: 8000
  strategy:
    blueGreen:
      activeService: python-test-active
      previewService: python-test-preview
