apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "color-grid.fullname" . }}-test-runner-{{ .Release.Revision }}
  labels:
    {{- include "color-grid.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "color-grid.labels" . | nindent 8 }}
      annotations:
        # This annotation ensures the Pod template is considered changed when the image changes
        checksum/test-image: {{ printf "%s:%s" .Values.testImage.repository .Values.testImage.tag | sha256sum }}
    spec:
      containers:
      - name: test-runner
        image: "{{ .Values.testImage.repository }}:{{ .Values.testImage.tag }}"
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0
