apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
spec:
  metrics:
  - name: success-rate
    successCondition: "result[1] >= 80.0"
    provider:
      prometheus:
        address: http://prometheus-server.default.svc.cluster.local
        query: |
          100* sum(rate(flask_http_request_total{status="200"}[30m]))/sum(rate(flask_http_request_total[30m]))
