apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: color-grid-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: color-grid
  template:
    metadata:
      labels:
        app: color-grid
    spec:
      containers:
      - name: color-grid
        image: devops0819/color-grid:20
        ports:
        - containerPort: 5000
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - analysis:
          templates:
          - templateName: success-rate-analysis
          args:
          - name: success-rate
            value: "80"
      - setWeight: 80
      - pause: {duration: 1m}
      - analysis:
          templates:
          - templateName: success-rate-analysis
          args:
          - name: success-rate
            value: "80"
      - setWeight: 100
