name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'Dockerfile.test'

env:
  APP_IMAGE_REPO: devops0819/color-grid
  TEST_IMAGE_REPO: devops0819/python-test

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.APP_IMAGE_REPO }}:run-${{ github.run_number }}

  build-and-push-test:
    runs-on: ubuntu-latest
    needs: build-and-push-app
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push test Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.test
          push: true
          tags: ${{ env.TEST_IMAGE_REPO }}:run-${{ github.run_number }}

  update-helm-values-and-create-pr:
    needs: build-and-push-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Update values.yaml with new image tags
        run: |
          sed -i "s/tag: .*/tag: 'run-${{ github.run_number }}'/" ./chart/values.yaml
          git add ./chart/values.yaml
          git commit -m "Update image tags to run-${{ github.run_number }}"
          git fetch --all
          git checkout -B auto-update-branch
          git push --set-upstream origin auto-update-branch --force

      - name: Create or update Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_PAT }}
          pr_title: "Auto-update image tags to run-${{ github.run_number }}"
          pr_body: "This is an automated pull request to update the image tags."
          destination_branch: "main"
          source_branch: "auto-update-branch"
