name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**' # Trigger only on changes within the helm directory

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    # Only run this job if the commit was not made by GitHub Actions
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:run-${{ github.run_number }}

  update-helm-values:
    # Only run this job if the commit was not made by GitHub Actions
    if: github.actor != 'github-actions[bot]'
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Update values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: \"run-${{ github.run_number }}\"/" ./chart/values.yaml

      - name: Commit and push the updated values.yaml
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./chart/values.yaml
          git commit -m "Update image tag to run-${{ github.run_number }}"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
