name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:run-${{ github.run_number }}

  update-helm-values-and-create-pr:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Create or reset the auto-update-branch
        run: |
          if git show-ref --verify --quiet refs/heads/auto-update-branch; then
            git checkout auto-update-branch
            git reset --hard origin/main
          else
            git checkout -b auto-update-branch
          fi

      - name: Update values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: \"run-${{ github.run_number }}\"/" ./chart/values.yaml

      - name: Commit and push the updated values.yaml
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./chart/values.yaml
          if git commit -m "Update image tag to run-${{ github.run_number }}"; then
            git push --force-with-lease https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} auto-update-branch
          else
            echo "No changes to commit."
          fi

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_PAT }}
          pr_title: "Auto-update image tag to run-${{ github.run_number }}"
          pr_body: "This is an automated pull request to update the image tag."
          destination_branch: "main"
          source_branch: "auto-update-branch"
