name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**' # Trigger only on changes within the helm directory

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:run-${{ github.run_number }}

  update-helm-chart:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Helm chart
      run: |
        sed -i 's/tag: .*/tag: "run-${{ github.run_number }}"/' ./helm/values.yaml
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git commit -am "Update image tag to run-${{ github.run_number }}"
        git push
