name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:${{ github.sha }}

      # AWS S3 validation steps
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: List Contents of S3 Bucket Directory (Validation)
        run: aws s3 ls s3://devops0819/charts/

      # Helm setup and deployment steps
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.8.0' # Use the specific Helm version needed

      - name: Install Helm S3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Add Helm repo
        run: |
          helm repo add my-helm-charts s3://devops0819/charts/
          helm repo update

      - name: Deploy with Helm
        run: |
          helm upgrade --install color-grid my-helm-charts/color-grid \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/color-grid \
            --set image.tag=${{ github.sha }} \
            --namespace default
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
