name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}:run-${{ github.run_number }}

  update-manifests-and-create-pr:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Update Kubernetes manifests with new image tag
        run: |
          sed -i "s|image: ${IMAGE_REPO}:.*|image: ${IMAGE_REPO}:run-${{ github.run_number }}|" ./chart/templates/*rollout.yaml
          git add ./chart/templates/*
          git commit -m "Update image tag to run-${{ github.run_number }}"
          git push --force-with-lease origin main

      - name: Create or update Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_PAT }}
          pr_title: "Auto-update image tag to run-${{ github.run_number }}"
          pr_body: "This is an automated pull request to update the image tag."
          destination_branch: "main"
          source_branch: "main"

  traffic-generation-and-checks:
    needs: update-manifests-and-create-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Assuming you are using requests library in your script

      - name: Run traffic generator script
        run: |
          python traffic_generator.py

      - name: Check Rollout status
        run: |
          kubectl argo rollouts status rollouts-name -n namespace --watch
