name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:${{ github.sha }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.9.0'

    - name: Add Helm S3 Plugin
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git

    - name: Add S3 Helm repository
      run: |
        helm repo add my-helm-charts s3://devops0819/charts/

    - name: Update Helm repositories
      run: |
        helm repo update

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install color-grid my-helm-charts/color-grid \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/color-grid \
          --set image.tag=${{ github.sha }} \
          --namespace default

    # Set up kubectl context
    - name: Set up Kubeconfig
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config

    # Verify kubectl context is set
    - name: Verify Kubernetes context
      run: |
        kubectl config current-context

    # Your Kubernetes deployment steps go here
