name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.9.0'
      
      - name: Install Helm S3 plugin
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git
          helm repo add my-helm-charts s3://devops0819/charts/
      
      - name: Update Helm repositories
        run: helm repo update
      
      - name: Deploy with Helm
        run: |
          helm upgrade --install color-grid my-helm-charts/color-grid \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/color-grid \
            --set image.tag=${{ github.sha }} \
            --namespace default
