name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:${{ github.sha }}

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Configure Helm directories and environment
        run: |
          mkdir -p ~/.helm/repository ~/.helm/plugins ~/.helm/starters ~/.helm/cache
          echo "HELM_HOME=$HOME/.helm" >> $GITHUB_ENV
          echo "XDG_CACHE_HOME=$HOME/.cache" >> $GITHUB_ENV
          echo "XDG_CONFIG_HOME=$HOME/.config" >> $GITHUB_ENV
          echo "XDG_DATA_HOME=$HOME/.local/share" >> $GITHUB_ENV

      - name: Install Helm S3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git || true

      - name: Add Helm repository
        run: helm repo add my-helm-charts s3://<your-s3-bucket-name>/charts/ || true

      - name: Deploy with Helm
        run: |
          helm repo update
          helm upgrade --install color-grid my-helm-charts/color-grid \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/color-grid \
            --set image.tag=${{ github.sha }} \
            --namespace default
