name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:run-${{ github.run_number }}

  update-helm-values-and-create-pr:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Create a unique branch for the update
        run: |
          git checkout -b update-image-${{ github.run_number }}

      - name: Update values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: \"run-${{ github.run_number }}\"/" ./chart/values.yaml
          git add ./chart/values.yaml
          git commit -m "Update image tag to run-${{ github.run_number }}"

      - name: Push changes
        run: |
          git push --set-upstream origin update-image-${{ github.run_number }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_PAT }}
          pr_title: "Auto-update image tag to run-${{ github.run_number }}"
          pr_body: "This is an automated pull request to update the image tag."
          destination_branch: "main"
          source_branch: "update-image-${{ github.run_number }}"
