name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - 'Dockerfile'
      - '*.py'
      - 'requirements.txt'

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}:run-${{ github.run_number }}

  update-image-and-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - run: |
          git fetch --all
          if git branch --list --remote | grep -q "origin/auto-update-branch"; then
            git checkout auto-update-branch
          else
            git checkout -b auto-update-branch
          fi

      - run: |
          sed -i "s|image: ${IMAGE_REPO}:.*|image: ${IMAGE_REPO}:run-${{ github.run_number }}|" ./chart/templates/rollout.yaml
          git add ./chart/templates/rollout.yaml
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update image tag to run-${{ github.run_number }}"
            git push --force-with-lease origin auto-update-branch

      - uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_PAT }}
          pr_title: "Auto-update image tag to run-${{ github.run_number }}"
          pr_body: "This is an automated pull request to update the image tag."
          destination_branch: "main"
          source_branch: "auto-update-branch"

  generate-traffic:
    needs: update-image-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          
      - run: |
          pip install -r requirements.txt
          python traffic-generator.py
