name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

env:
  IMAGE_REPO: devops0819/color-grid

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:run-${{ github.run_number }}

  update-helm-values-and-create-pr:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Checkout or create the auto-update-branch
        run: |
          git fetch origin auto-update-branch:auto-update-branch || git branch auto-update-branch
          git checkout auto-update-branch

      - name: Rebase onto main
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Update values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: \"run-${{ github.run_number }}\"/" ./chart/values.yaml
          if git diff --exit-code --quiet; then
            echo "No changes to commit."
            exit 78  # Exiting with a specific code to indicate no changes.
          else
            git add ./chart/values.yaml
            git commit -m "Update image tag to run-${{ github.run_number }}"
            git push --force-with-lease origin auto-update-branch
          fi

      - name: Create Pull Request
        if: ${{ success() && steps.commit-and-push.outcome != 'skipped' }}
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GH_PAT }}
          pr_title: "Auto-update image tag to run-${{ github.run_number }}"
          pr_body: "This is an automated pull request to update the image tag."
          destination_branch: "main"
          source_branch: "auto-update-branch"
