name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.9.0'

      - name: Install Helm S3 plugin
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git
          helm repo add my-helm-charts s3://devops0819/charts/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'

      - name: Setup Kubernetes context
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_BASE64}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Helm repositories
        run: helm repo update

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install color-grid my-helm-charts/color-grid \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/color-grid \
            --set image.tag=${{ github.sha }} \
            --namespace default
