name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/color-grid:${{ github.sha }}

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest'
      
    - name: Create Helm directories and set HELM_HOME
      run: |
          mkdir -p ~/.helm/plugins
          mkdir -p ~/.helm/repository
          mkdir -p ~/.helm/cache
          mkdir -p ~/.helm/starters
          echo "HELM_HOME=$HOME/.helm" >> $GITHUB_ENV
      
    - name: Configure Helm S3 Plugin
      run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git
          helm repo add my-helm-charts s3://devops0819/charts/

    - name: Update Helm repositories
      run: helm repo update
        
    - name: Push Helm chart to S3 bucket
      run: helm s3 push color-grid-0.1.0.tgz my-helm-charts

    - name: Deploy application using Helm
      run: |
        helm upgrade --install color-grid my-helm-charts/color-grid --namespace default --set image.tag=${{ github.sha }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'ap-south-1'
