name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.x'

      - name: Install Helm S3 Plugin
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Add Helm Repo
        run: |
          helm repo add my-helm-charts s3://devops0819/charts/
          helm repo update

      - name: Deploy Application
        run: |
          helm upgrade --install color-grid my-helm-charts/color-grid --version "0.1.0" \
            --set image.repository=your-docker-image-repo/color-grid \
            --set image.tag=your-image-tag \
            --namespace default
        env:
          HELM_EXPERIMENTAL_OCI: 1
